### ISSUE TITLE
\\[\n\\begin{align*}\n\\frac{dR}{dt} &= \\alpha R - \\beta R P \\\\\n\\frac{dP}{dt} &= \\delta R P - \\gamma P\n\\end{align*}\n\\] error

### ISSUE THREAD

**Issue by duwei1314gd** [SchneeHertz/markdown-it-katex-gpt#1]
![image](https://github.com/user-attachments/assets/ffc404c3-3b7f-4721-b6db-bba5c4a6de1e)
你好 可以问一下这种返回报错原因吗？

**Comment by SchneeHertz** [comment]
gpt说align是一个特殊的包，默认是不带的
```
\\[
\\frac{dR}{dt} = \\alpha R - \\beta R P
\\]
\\[
\\frac{dP}{dt} = \\delta R P - \\gamma P
\\]
```
这样是能正常显示的

更新：
见下条回复，katex对align命令有特别的处理，这里应该使用aligned

**Comment by duwei1314gd** [comment]
后端没有写prompt  那只能前端去替换吗

**Comment by SchneeHertz** [comment]
可以参考 #https://github.com/KaTeX/KaTeX/issues/1007
gpt生成的内容只能尽量处理，边界情况不太可能完全考虑到

**Comment by duwei1314gd** [comment]
align* 替换为 aligned  就好了  暂时解决  报错原因是  要使用显示模式就很头大
