### ISSUE TITLE
$$不能正常展示

### ISSUE THREAD

**Issue by richness** [SchneeHertz/markdown-it-katex-gpt#2]
$$不能正常展示，并且该插件只能行展示，大神，后期还对块公式支持吗？

**Comment by richness** [comment]
import '@/styles/common/global.scss';
import { createApp } from 'vue';
import App from './App.vue';
import pinia from './store/index';
import 'virtual:svg-icons-register';
import SvgIcon from '@/components/SvgIcon.vue';
import router from './router/index';
// 预览组件以及样式
import VMdPreview from '@kangc/v-md-editor/lib/preview';
import '@kangc/v-md-editor/lib/style/preview.css';
import hljs from 'highlight.js';
import githubTheme from '@kangc/v-md-editor/lib/theme/github.js';
import '@kangc/v-md-editor/lib/theme/style/github.css';
import markdownItKatexGpt from 'markdown-it-katex-gpt'; // 方式3
// 引入v-md-editor预览组件
VMdPreview.use(githubTheme, {
  Hljs: hljs,
  extend(mdInstance) {
    mdInstance.use(markdownItKatexGpt, {
      delimiters: [
        { left: '$', right: '$', display: false },
        { left: '$$', right: '$$', display: true },
        { left: '\\(', right: '\\)', display: false },
        { left: '\\[', right: '\\]', display: true },
      ],
    });
  },
});

// 创建vue实例
const vueApp = createApp(App);

vueApp.use(pinia).use(router);
vueApp.use(VMdPreview);
vueApp.component('SvgIcon', SvgIcon);
vueApp.mount('#app');

let text1 = ref('\\(F = G\\frac{m_1m_2}{r^2}\\)');
let text2 = ref('\\[F = G\\frac{m_1m_2}{r^2}\\]');
let text3 = ref('$F=G\\frac{m_1m_2}{r^2}$');
let text4 = ref('$$F = G\\frac{m_1m_2}{r^2}$$');

  <v-md-preview :text="text1" class="question-text"> </v-md-preview>
 <v-md-preview :text="text2" class="question-text"> </v-md-preview>
<v-md-preview :text="text3" class="question-text"> </v-md-preview>
<v-md-preview :text="text4" class="question-text"> </v-md-preview>
![221a72df-a9ce-4323-8d88-7b2cd1545f2a](https://github.com/user-attachments/assets/a7a615ac-5d5f-4a39-966a-107333fbe775)

你好，对应text4,$$公式展示异常，该如何解决呢？

**Comment by SchneeHertz** [comment]
\是用来转义\的
应该这么写：
```
mdInstance.use(markdownItKatexGpt, {
  delimiters: [
    { left: '\\[', right: '\\]' },
    { left: '\\(', right: '\\)' },
    { left: '$$', right: '$$' },
    { left: '$', right: '$' }
  ]
})
let text1 = ref('\\(F = G\\frac{m_1m_2}{r^2}\\)');
let text2 = ref('\\[F = G\\frac{m_1m_2}{r^2}\\]');
let text3 = ref('$F=G\\frac{m_1m_2}{r^2}$');
let text4 = ref('$$F = G\\frac{m_1m_2}{r^2}$$');
```

**Comment by SchneeHertz** [comment]
块公式指的是display选项吗，已经加上了

**Comment by richness** [comment]
我知道问题所在了，
 // { left: '$', right: '$', display: false },
        { left: '\\[', right: '\\]', display: true },
        { left: '\\(', right: '\\)', display: false },
        { left: '$$', right: '$$', display: false },
        框架中$对$$有影像，如果只设置$$,let text4 = ref('$$F = G\\frac{m_1m_2}{r^2}$$');公式就可以正常展示，但是对只有$的就不能展示了。

**Comment by SchneeHertz** [comment]
> 我知道问题所在了， // { left: '$', right: '$', display: false }, { left: '\[', right: '\]', display: true },{ left: '\[', right: '\]', display: true } { left: '\(', right: '\)', display: false },{ left: '\（', right: '\）', display: false } { left: '$$', right: '$$', display: false },{ left: '$$', right: '$$', display: false } 框架中$对$$有影像，如果只设置$$,let text4 = ref('$$F = G\frac{m_1m_2}{r^2}$$');公式就可以正常展示，但是对只有$的就不能展示了。

分隔符列表是从前到后处理的，你可以把{ left: '$', right: '$', display: false }放在{ left: '$$', right: '$$', display: false }后面，这样既能匹配到$$，也不影响$的匹配

**Comment by richness** [comment]
太感谢您了，真的是这样。非常感谢您。解决了。

**Comment by richness** [comment]
对于display选项，需要引入css吗？我看目前都是按照行展示的。

**Comment by SchneeHertz** [comment]
> 对于display选项，需要引入css吗？我看目前都是按照行展示的。

在1.1.0版本，这个选项对应到katex的displayMode选项，不需要css就可以使用
