### ISSUE TITLE
katex.mjs:478 LaTeX-incompatible input and strict mode is set to 'warn': Unicode text character "常" used in math mode [unicodeTextInMathMode]

### ISSUE THREAD

**Issue by xuelin-cell** [SchneeHertz/markdown-it-katex-gpt#3]
您好：我在安卓的webview中加载前端页面，遇到了这个错误，您了解怎么解决吗？iOS渲染公式是没有问题的。
![image](https://github.com/user-attachments/assets/3162bd08-a0b3-4048-9410-4f0d1b27523c)

**Comment by SchneeHertz** [comment]
没有安卓开发的经验，不清楚
